# Site settings
title:          Durgesh Gupta Blog
description:    "Durgesh Gupta Blog"
baseurl:        ""
url:            ""

# Author
author:
  name:         Dugresh Gupta
  url:          https://durgeshgupta.com
  email:        durgesh@durgeshgupta.com

# Build settings
markdown:       kramdown

# Assets
sass:
  sass_dir:     _sass
  style:        compressed

# Gems
plugins:
  - jekyll-paginate

# Permalinks
permalink:      /:year-:month-:day/:title
paginate:       5
